# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://localhost:8000/chapter
Content-Type: application/json

{
  "title": "DB 챕터",
  "description": "이제 진짜 DB에 저장된다"
}
